Entity/Page.php
<?php

namespace Emr\CMBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\MappedSuperclass()
 */
abstract class Page
{
    /**
     * @var integer
     * @ORM\Id()
     * @ORM\Column(type="smallint")
     * @ORM\GeneratedValue()
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(name="_key", length=32)
     */
    protected $key;

    /**
     * @var string
     * @ORM\Column()
     */
    protected $name;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $menuView = true;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $menuPosition = 10;

    /**
     * Will be configured as many to one
     * @var LocalizedConstant
     */
    protected $constant;

    public function getId()
    {
        return $this->id;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey(string $key)
    {
        $this->key = $key;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function getMenuView()
    {
        return $this->menuView;
    }

    public function setMenuView(bool $menuView)
    {
        $this->menuView = $menuView;
    }

    public function getMenuPosition()
    {
        return $this->menuPosition;
    }

    public function setMenuPosition($menuPosition)
    {
        $this->menuPosition = $menuPosition;
    }

    public function setConstant(LocalizedConstant $constant)
    {
        $this->constant = $constant;
    }

    public function getConstant(): ?LocalizedConstant
    {
        return $this->constant;
    }

    public function getSettings()
    {
        $this->getConstant();
    }

    public function setSections($sections)
    {
        foreach ($sections as $section)
            $this->{$section['property']} = (new $section['class']())->addPage($this);
    }

    public function getSections()
    {
        return [];
    }

    public function getLocale()
    {
        return $this->getConstant()->getLocale();
    }

    public function __toString()
    {
        return (string) $this->key . ' / ' . $this->constant;
    }
}

Resources/views/admin/dashboard.html.twig
{% extends '@EasyAdmin/default/layout.html.twig' %}

{% set _content_title = 'Dashboard'|trans %}

{% block page_title -%}
    {{ _content_title }}
{%- endblock %}

{% block content_header %}
    <h1 class="title">{{ _content_title }}</h1>
{% endblock %}

{% block main %}
    <div class="section">
        <h3 class="section-title">Hızlı işlemler</h3>
        <div class="section-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="box box-primary">
                        <strong class="box-header with-border">Sayfaları düzenle</strong>
                        {% for item in edit_pages %}
                            <a href="{{ path('easyadmin', { entity: 'CMSPageLayout', action: 'section', _key: item.key }) }}" class="box-body">
                                <i class="fa fa-file-text fa-fw"></i>
                                &nbsp;{{ item.name }}
                            </a>
                        {% else %}
                            <div class="box-body">Henüz sayfalarınız oluşturulmamış. Lütfen yöneticinize başvurun.</div>
                        {% endfor %}
                    </div>
                </div>
                {% for entity in edit_entities|default([]) %}
                    <div class="col-sm-4">
                        <div class="box box-primary">
                            <strong class="box-header with-border">{{ entity.title|default(entity.name)|trans }}</strong>
                            <a href="{{ path('easyadmin', { entity: entity.name, action: 'new' }) }}" class="box-body body-header" style="">
                                <strong><i class="fa fa-plus-circle fa-fw"></i> Yeni ekle</strong>
                            </a>
                            {% if entity.rows|length > 0 %}
                                {% for row in entity.rows %}
                                    <a href="{{ path('easyadmin', { entity: entity.name, action: 'edit', id: row.id }) }}" class="box-body body-row">
                                        <i class="fa fa-file-o fa-fw" style="transform: scale(.8);"></i>
                                        {% set label = attribute(row, entity.identifier) %}
                                        &nbsp;{{ label[:35] ~ (label|length > 35 ? '...') }}
                                    </a>
                                {% endfor %}
                                <a href="{{ path('easyadmin', { entity: entity.name, action: 'list' }) }}" class="box-body body-footer" style="border-top: 1px solid #f4f4f4;">
                                    <strong><i class="fa fa-list-ul fa-fw"></i> Tümünü listele</strong>
                                </a>
                            {% else %}
                                <div class="box-body">Henüz kayıt yok.</div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block head_stylesheets %}
    {{ parent() }}
    <style>
        .box > .box-body {
            display: block;
        }
        .box-body.body-header {
            border-bottom: 1px solid #f4f4f4;
        }
        .box-body.body-footer {
            border-top: 1px solid #f4f4f4;
        }
        .box-body.body-row {
            padding: 5px 10px;
        }

        .section {
            margin: 0 -15px;
            border-top: 5px solid rgba(0, 0, 0, .04);
            background: rgba(0, 0, 0, .02);
        }
        .section:nth-child(even) {
            background: #fff;
        }
        .section-title {
            margin: 0;
            padding: 15px;
        }
        .section-body {
            padding: 5px 15px 20px;
        }
        .section-body .box {
            margin: 0;
        }
        .section:nth-child(even) .box {
            background: rgba(0, 0, 0, .01);
        }
    </style>
{% endblock %}

Resources/views/admin/list_locale.html.twig
{% extends '@EasyAdmin/default/list.html.twig' %}

{% block table_head %}{% endblock table_head %}

{% block table_body %}
    {% for item in paginator.currentPageResults %}
        {% set _item_id = '' ~ attribute(item, _entity_config.primary_key_field_name) %}
        <tr data-id="{{ _item_id }}">
            {% set metadata = fields.locale %}
            {% set isSortingField = metadata.property == app.request.get('sortField') %}
            {% set _column_label =  (metadata.label ?: "Locale")|trans(_trans_parameters)  %}

            <td data-label="{{ _column_label }}" class="{{ isSortingField ? 'sorted' }} {{ metadata.dataType|lower }} {{ metadata.css_class }}">
                {{ (easyadmin_render_field_for_list_view(_entity_config.name, item, metadata)|trim)|intl_language }}
            </td>

            {% if _list_item_actions|length > 0 %}
                {% set _column_label =  'list.row_actions'|trans(_trans_parameters, 'EasyAdminBundle') %}
                <td data-label="{{ _column_label }}" class="actions">
                    {% block item_actions %}
                        {{ include('@EasyAdmin/default/includes/_actions.html.twig', {
                            actions: _list_item_actions,
                            request_parameters: _request_parameters,
                            translation_domain: _entity_config.translation_domain,
                            trans_parameters: _trans_parameters,
                            item_id: _item_id
                        }, with_context = false) }}
                    {% endblock item_actions %}
                </td>
            {% endif %}
        </tr>
    {% else %}
        <tr>
            <td class="no-results" colspan="{{ _list_item_actions|length > 0 ? fields|length + 1 : fields|length }}">
                {{ 'search.no_results'|trans(_trans_parameters, 'EasyAdminBundle') }}
            </td>
        </tr>
    {% endfor %}
{% endblock table_body %}

Resources/views/admin/menu.html.twig
{% extends '@EasyAdmin/default/menu.html.twig' %}

{% import _self as helper %}

{% block menu_item %}
    {% if not cms_config['easy_admin_settings']['use_security'] or item.role_require is not defined or (item.role_require and is_granted(item.role_require)) %}
        {{ parent() }}
    {% endif %}
{% endblock menu_item %}

{% block main_menu %}
    {% for item in _menu_items %}
        {% if item.embed_pages|default(false) %}
            {% for page in menu_pages %}
                {% set item = item|merge({
                    'label': page.name,
                    'params': item.params|merge({'_key': page.key})
                }) %}
                <li class="{{ app.request.query.get('_key') == page.key ? 'active' }}">
                    {{ helper.render_menu_item(item, _entity_config.translation_domain|default('messages')) }}
                </li>
            {% endfor %}
        {% else %}
            {{ block('menu_item') }}
        {% endif %}
    {% endfor %}
{% endblock main_menu %}

Resources/views/admin/section_list.html.twig
{% extends '@EasyAdmin/default/list.html.twig' %}

{% block main %}
    {% set column = pages|length > 0 and pages|length < 4 ? pages|length : 2 %}
    <div class="row">
        {% for page in pages %}
            <div class="col-md-{{ 12/column }}">
                <h3><strong>{{ intl_language(page.constant.locale, app.request.locale) }}</strong></h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><span>{{ 'Section'|trans }}</span></th>
                            <th><span>{{ 'Edit'|trans }}</span></th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for section in sections %}
                        {% set sectionObj = attribute(page, section.property) %}
                        {% if sectionObj %}
                            {% set _request_parameters = {
                                menuIndex: app.request.get('menuIndex'),
                                submenuIndex: app.request.get('submenuIndex'),
                                page: app.request.get('page', 1),
                                _key: app.request.get('_key'),
                            } %}
                            {% set _referer = _request_parameters|merge({
                                entity: app.request.get('entity'),
                                action: 'section',
                                _key: app.request.get('_key'),
                            }) %}
                            {% set entityName = easyadmin_entity_name(section.class) %}
                            {% set entityConfig = easyadmin_entity(entityName) %}
                            {% if entityConfig.redirect is defined and entityConfig.redirect is not empty %}
                                {% set _request_parameters = _request_parameters|merge(entityConfig.redirect is iterable ? entityConfig.redirect|merge({'entity':easyadmin_entity_name(entityConfig.redirect.entity)}) : {'entity': easyadmin_entity_name(entityConfig.redirect)}) %}
                            {% else %}
                                {% set _request_parameters = _request_parameters|merge({ entity: entityName, action: 'edit', id: attribute(sectionObj, 'id') }) %}
                            {% endif %}
                            <tr>
                                <td>
                                    {{ sectionObj.identifier|default(section.label|default(section.property|humanize)|trans) }}
                                </td>
                                <td class="actions">
                                    <a class="text-primary action-edit" href="{{ path('easyadmin', _request_parameters|merge({referer: path('easyadmin', _referer)|url_encode})) }}">{{ 'Edit'|trans }}</a>
                                </td>
                            </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock main %}

{% block head_stylesheets %}
    {{ parent() }}
    <style> h3 { margin-top: 0; } </style>
{% endblock head_stylesheets %}